"""What the control map claims, checked against the system it claims it of.

The ordinary fate of compliance documentation is to describe a system it has
stopped matching, and the reason auditors discount it. The mechanism against
that is here: every row of `docs/compliance/soc2-controls.md` names a pytest
node id, and a control whose test is renamed or deleted fails the build.

Two tests in this file are themselves named by the map, which is deliberate —
the hardening controls have to be evidenced by something, and the something
should be the test that exercises them.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from engine.api.hardening import (
    API_CSP, RATE_LIMIT_SCOPE, SECURITY_HEADERS, UI_CSP, RateLimit,
)
from engine.report.compliance import (
    CONTROLS, Control, compliance, read_controls, unresolved_evidence,
)

ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture(scope="module")
def controls():
    return read_controls(ROOT / CONTROLS)


@pytest.fixture(scope="module")
def collected():
    """Every node id pytest collects, asked of pytest itself.

    Collected rather than globbed for `def test_`: a test inside a class, or
    one generated by a fixture, is collected and would not be found by
    reading the source — and a check that under-counts the suite would report
    a live test as missing.
    """
    out = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "--no-header",
         "-p", "no:cacheprovider"],
        cwd=ROOT, capture_output=True, text=True, timeout=900,
    )
    assert out.returncode == 0, out.stdout[-3000:] + out.stderr[-2000:]
    ids = [line.strip().split("[", 1)[0]
           for line in out.stdout.splitlines()
           if "::" in line and not line.startswith(("=", "<", "ERROR"))]
    assert ids, "collected no tests at all"
    return ids


# --------------------------------------------------------------------------
# The rule that keeps the map honest
# --------------------------------------------------------------------------

def test_every_control_names_evidence_that_still_exists(controls, collected):
    """**G2's acceptance criterion.** A named test that disappeared fails here.

    This is the whole reason the control map is worth writing down. Without
    it the document drifts from the system silently, and its value to an
    auditor is the value of any unverified assertion.
    """
    missing = unresolved_evidence(controls, collected)
    assert not missing, (
        f"controls cite tests the suite no longer collects: {missing}. Either "
        f"the test was renamed — update the map — or the mechanism is gone, "
        f"in which case the control is no longer satisfied."
    )


def test_every_claimed_control_actually_names_something(controls):
    """Guards a row that satisfies the check above by naming nothing.

    `unresolved_evidence` compares the ids a row *has*. A row with an empty
    evidence cell has none to be missing, so it would pass silently — the
    empty-collection failure, one column over.
    """
    silent = [c.control for c in controls
              if c.claimed and not c.node_ids and not c.generated]
    assert not silent, (
        f"controls {silent} claim to be satisfied and cite no test and no "
        f"generated artifact; they pass the evidence check by having no "
        f"evidence to check"
    )


def test_the_map_records_its_gaps_rather_than_only_its_wins(controls):
    """Guards a control map whose totals are a function of what was written.

    A map with no unsatisfied rows is a map nobody audited. The first
    question a good auditor asks is what is missing, and a document that
    cannot answer it has answered it.
    """
    unclaimed = [c for c in controls if not c.claimed]
    assert unclaimed, (
        "no control is marked 'not claimed'. Either every Trust Services "
        "criterion this system touches is genuinely satisfied — which would "
        "be remarkable — or the gaps stopped being written down."
    )


def test_a_control_map_that_parses_to_nothing_is_an_error(tmp_path):
    """Guards the shape this repo keeps being bitten by.

    An empty parse reports zero unresolved references, which is byte-identical
    to a clean bill of health. A renamed heading or a reformatted table would
    produce it.
    """
    empty = tmp_path / "soc2-controls.md"
    empty.write_text("# SOC 2 control map\n\nNo tables here.\n")
    with pytest.raises(ValueError, match="zero controls"):
        read_controls(empty)

    with pytest.raises(FileNotFoundError):
        read_controls(tmp_path / "absent.md")


def test_the_generated_section_says_when_it_did_not_check(controls):
    """Guards an unchecked binder reading like a checked one.

    Built without a test inventory, the section cannot verify a single
    reference. Reporting that identically to a verified build is the same
    defect as a skipped measurement reading as a passing one.
    """
    unchecked = compliance([], ROOT / CONTROLS)
    assert unchecked["evidence_checked"] is False
    assert unchecked["unresolved_evidence"] == {}, (
        "with nothing collected, every reference is trivially 'missing' or "
        "trivially 'fine'; the flag is what distinguishes them"
    )


def test_the_section_stays_available_even_with_unsatisfied_controls():
    """§1.5's rule, at the section level.

    `available=False` means "this pack could not look", not "this pack looked
    and found gaps". Collapsing the two would let a build that failed to read
    the map look like a system with nothing to report.
    """
    content = compliance([], ROOT / CONTROLS)
    assert content["available"] is True
    assert content["n_not_claimed"] > 0


# --------------------------------------------------------------------------
# The hardening controls, evidenced by the tests the map names
# --------------------------------------------------------------------------

def test_every_response_carries_the_headers_that_matter_for_json():
    """**Named by CC6.6.**

    `nosniff` is the one that matters most: without it a browser may sniff a
    JSON response as HTML and execute it, which is the path from "returns
    user data" to "runs script in the API's origin". `no-referrer` because
    run ids are request fingerprints and a referrer leaks them onward;
    `no-store` because results are a tenant's numbers and a shared cache
    holding them is a cross-tenant read no route check can see.
    """
    pytest.importorskip("fastapi")
    from fastapi.testclient import TestClient

    from engine.api import create_app

    with TestClient(create_app(max_workers=1)) as client:
        response = client.get("/models")
        for header, value in SECURITY_HEADERS.items():
            assert response.headers.get(header) == value, header
        assert response.headers.get("Content-Security-Policy") == API_CSP
        assert response.headers.get("Cache-Control") == "no-store"

        # The UI needs its own two assets, so it gets a different policy —
        # and must not be handed `default-src 'none'`, which would render a
        # blank page while every header looked correct.
        page = client.get("/ui")
        assert page.headers.get("Content-Security-Policy") == UI_CSP
        assert "'self'" in UI_CSP and "'self'" not in API_CSP


def test_hsts_is_not_emitted_by_the_application():
    """Guards a header that promises something this process cannot know.

    Strict-Transport-Security is a promise about a *scheme*. This process
    does not know whether it sits behind TLS: emitted from a plain-HTTP
    deployment it does nothing, and where TLS does terminate the header
    belongs on the proxy holding the certificate. A header that is present
    and meaningless is worse than absent, because it is read as coverage.
    """
    assert not any(h.lower() == "strict-transport-security"
                   for h in SECURITY_HEADERS)


def test_the_rate_limit_states_what_it_is_not():
    """**Named by A1.1.**

    A control believed to do more than it does is worse than no control,
    because it stops anyone looking. This limiter is per-process, so N
    replicas admit N times the rate, and it is not a DoS control because an
    unauthenticated caller never reaches it. Both sentences have to survive.
    """
    for required in ("NOT a distributed limit", "NOT a denial-of-service",
                     "own buckets"):
        assert required in RATE_LIMIT_SCOPE, (
            f"the rate limit's scope stopped saying {required!r}"
        )


def test_the_rate_limit_admits_the_rate_and_then_refuses():
    """The mechanism behind the claim, so A1.1 is not evidenced by prose alone."""
    limit = RateLimit(rate=3, window=60.0)
    assert [limit.check("k", now=0.0) for _ in range(3)] == [True] * 3
    assert limit.check("k", now=0.0) is False
    # A different key is a different bucket, or one noisy client would take
    # everyone else's quota with it.
    assert limit.check("other", now=0.0) is True
    # And the window slides rather than resetting: a fixed window admits
    # twice the rate across its boundary.
    assert limit.check("k", now=60.1) is True


def test_retry_after_is_never_zero():
    """Guards a rate limit that becomes a busy loop.

    `Retry-After: 0` invites an immediate retry which also fails. A
    well-behaved client and a correct server then spin against each other.
    """
    limit = RateLimit(rate=1, window=60.0)
    limit.check("k", now=0.0)
    assert limit.retry_after("k", now=59.99) >= 1
    assert limit.retry_after("never-seen", now=0.0) >= 1


def test_a_rate_limited_response_still_carries_the_security_headers():
    """Guards the error path losing the headers the success path has.

    A 429 is generated before the middleware's normal response path, which is
    exactly the kind of early return that ships without them.
    """
    pytest.importorskip("fastapi")
    from fastapi.testclient import TestClient

    from engine.api import create_app

    with TestClient(create_app(max_workers=1, rate_limit=2)) as client:
        for _ in range(2):
            client.get("/models")
        blocked = client.get("/models")
        assert blocked.status_code == 429
        assert blocked.headers.get("Retry-After")
        for header, value in SECURITY_HEADERS.items():
            assert blocked.headers.get(header) == value, header


def test_health_is_never_rate_limited():
    """Guards a liveness probe that a busy client can turn into an outage.

    `/health` is the one route with no role requirement because a load
    balancer has no token. For the same reason it must not be the route that
    starts failing when some other client is noisy — the orchestrator would
    read 429 as unhealthy and restart a pod that is fine.
    """
    pytest.importorskip("fastapi")
    from fastapi.testclient import TestClient

    from engine.api import create_app

    with TestClient(create_app(max_workers=1, rate_limit=1)) as client:
        client.get("/models")
        assert client.get("/models").status_code == 429
        for _ in range(5):
            assert client.get("/health").status_code == 200


def test_the_limiter_is_off_unless_a_deployment_asks_for_it():
    """The library and the local demo must behave as they did.

    Same posture as authentication and tenancy: a capacity decision belongs
    to a deployment, and a library that silently rate-limits its caller is a
    library with an opinion about a program it cannot see.
    """
    pytest.importorskip("fastapi")
    from fastapi.testclient import TestClient

    from engine.api import create_app

    with TestClient(create_app(max_workers=1)) as client:
        for _ in range(50):
            assert client.get("/health").status_code == 200


# --------------------------------------------------------------------------
# The map's own prose
# --------------------------------------------------------------------------

def test_the_map_carries_the_leak_it_would_rather_not_mention(controls):
    """Guards the inconvenient sentence being quietly dropped.

    A security posture is worth what its most inconvenient sentence is worth.
    Cross-tenant compute deduplication leaves a liveness oracle, and a control
    map that omits it is describing a different system.
    """
    text = (ROOT / CONTROLS).read_text(encoding="utf-8").lower()
    assert "liveness oracle" in text
    assert "dedupe_across_tenants" in text

    content = compliance([], ROOT / CONTROLS)
    assert content["shared_compute_leak"], (
        "the generated section carries no leak statement, so the binder an "
        "auditor receives omits what the document says"
    )
