"""IFRS 17's liability for incurred claims, and the triangle behind it.

RFC-012 built the liability for remaining coverage under the general model,
RFC-013 under the variable fee approach and RFC-017 under the premium
allocation approach. All three named the same thing as out of scope, and
RFC-017 named it as a separate RFC:

> **The liability for incurred claims.** §59(b) permits it undiscounted
> where claims settle within a year, and requires discounting and a risk
> adjustment otherwise. It is a separate balance from the LRC and a
> separate RFC.

This is it. The LIC is the other half of an insurance contract liability:
what is owed for events that have already happened, as against what is owed
for cover not yet given.

The structural point: the LIC has no CSM
----------------------------------------
A contractual service margin is unearned profit, and a claim that has been
incurred has consumed the service it was paid for. So when a claim moves
from the LRC to the LIC it takes no margin with it — the profit on that
service was recognised as the coverage was provided, and what remains is a
liability measured at fulfilment value and nothing else:

    LIC = present value of future claim payments  +  risk adjustment

Two components, not three. That is why the LIC roll-forward has a different
shape from RFC-012's and why it cannot absorb a change in estimate the way a
CSM can: an adverse development on incurred claims goes **straight to
profit**, with nothing to cushion it. Under the general model, the identical
adverse development on *future* claims is absorbed by the CSM and never
appears. The two halves of the same balance sheet treat the same news
completely differently, and which half it lands in is a question of timing.

The reconciliation invariant
----------------------------
The same discipline every reporting overlay here is checked against, with
one term that is easy to leave out. Over the whole run-off,

    opening liability
        + insurance service expense
        + insurance finance expense
        = total claims paid

The **opening balance is not an expense of this run-off**. It was
recognised as the claims were incurred, in the period the coverage was
provided; what the LIC recognises afterwards is only the unwind of the
discount and the release of the risk adjustment. An invariant written
without that term is wrong by the whole liability, which is large enough to
notice and exactly the sort of thing that gets asserted rather than
measured. :meth:`Measurement.reconciles` carries it.

The chain ladder is exact, and then it is not
---------------------------------------------
:func:`chain_ladder` estimates ultimates from a run-off triangle by
volume-weighted development factors. On a triangle generated by a single
development pattern it recovers the ultimates **exactly** — that is the
golden test, and it is asserted to 1e-12.

It stops being exact the moment two different patterns are in the same
triangle, which is what combining segments does. See RFC-023 for the size
of it: the chain ladder is **not additive**, so the reserve for a combined
book differs from the sum of the reserves for its parts, and the difference
is not a rounding.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from engine.data.rates import YieldCurve
from engine.report.ifrs17 import TIMINGS, RiskAdjustment, _timed_factors

#: How development factors are averaged across accident periods.
FACTOR_METHODS = ("volume", "simple")


class Triangle:
    """Cumulative claims by accident period and development period.

    ``triangle[i, j]`` is everything paid on accident period ``i`` by the
    end of development period ``j``, so the observed cells are those with
    ``i + j < n`` — the upper-left triangle — and the diagonal
    ``i + j == n − 1`` is the latest position of each accident period.

    Accepts a ragged list of rows (row ``i`` has ``n − i`` entries) or a
    square array with ``nan`` in the unobserved corner. Both are stored the
    second way, because the completed square is what everything downstream
    wants.
    """

    def __init__(self, rows, *, cumulative: bool = True):
        if isinstance(rows, np.ndarray) and rows.ndim == 2:
            data = np.array(rows, dtype=np.float64)
            if data.shape[0] != data.shape[1]:
                raise ValueError(
                    f"a run-off triangle is square, got {data.shape}"
                )
        else:
            rows = [np.asarray(r, dtype=np.float64).ravel() for r in rows]
            n = len(rows)
            lengths = [r.size for r in rows]
            if lengths != [n - i for i in range(n)]:
                raise ValueError(
                    f"row i must have n − i entries; got {lengths} for "
                    f"{n} accident periods"
                )
            data = np.full((n, n), np.nan)
            for i, row in enumerate(rows):
                data[i, :row.size] = row
        n = data.shape[0]
        if n < 2:
            raise ValueError("a triangle needs at least two accident periods")
        observed = ~np.isnan(data)
        expected = np.arange(n)[:, None] + np.arange(n)[None, :] < n
        if not np.array_equal(observed, expected):
            raise ValueError(
                "the observed cells are not the upper-left triangle; a hole "
                "in a triangle is a data problem, not a shape to guess at"
            )
        if not cumulative:
            data = np.nancumsum(np.where(observed, data, 0.0), axis=1)
            data[~expected] = np.nan
        if np.any(data[observed] < 0.0):
            raise ValueError("cumulative claims paid cannot be negative")
        self.n_periods = n
        self.cumulative = data

    @classmethod
    def from_pattern(cls, ultimates, pattern) -> "Triangle":
        """A triangle generated by one development pattern, exactly.

        ``pattern`` is the cumulative share paid by the end of each
        development period, ending at 1.0. The chain ladder recovers
        ``ultimates`` from the result to floating point, which is the
        golden test: an estimator that cannot invert its own generating
        process is not estimating anything.
        """
        ultimates = np.asarray(ultimates, dtype=np.float64).ravel()
        pattern = np.asarray(pattern, dtype=np.float64).ravel()
        n = ultimates.size
        if pattern.size != n:
            raise ValueError(
                f"{n} accident periods needs {n} development periods, got "
                f"{pattern.size}"
            )
        if np.any(np.diff(pattern) < 0.0):
            raise ValueError("a cumulative payment pattern cannot go down")
        if pattern[-1] <= 0.0:
            raise ValueError("a payment pattern that pays nothing is not one")
        full = ultimates[:, None] * pattern[None, :]
        full[np.arange(n)[:, None] + np.arange(n)[None, :] >= n] = np.nan
        return cls(full)

    def incremental(self) -> np.ndarray:
        """Paid in each development period, ``nan`` where unobserved."""
        increments = np.diff(self.cumulative, axis=1, prepend=0.0)
        increments[np.isnan(self.cumulative)] = np.nan
        return increments

    def latest(self) -> np.ndarray:
        """Paid to date on each accident period — the leading diagonal."""
        n = self.n_periods
        return np.array([self.cumulative[i, n - 1 - i] for i in range(n)])

    def paid_to_date(self) -> float:
        return float(self.latest().sum())

    def __repr__(self) -> str:
        return f"Triangle({self.n_periods} accident periods)"

    def __fingerprint__(self):
        return {"n_periods": self.n_periods, "cumulative": self.cumulative}


def development_factors(triangle: Triangle, method: str = "volume"
                        ) -> np.ndarray:
    """Age-to-age factors, ``n − 1`` of them.

    ``"volume"`` — the standard chain ladder: the ratio of column totals,
    which weights each accident period by how much of it has developed.

    ``"simple"`` — the unweighted mean of the individual ratios, which gives
    a barely developed accident period the same say as a nearly closed one.

    Neither is more correct in the abstract; they answer different questions
    and they disagree whenever the accident periods are of different sizes,
    which they always are.
    """
    if method not in FACTOR_METHODS:
        raise ValueError(
            f"factor method must be one of {FACTOR_METHODS}, got {method!r}"
        )
    data = triangle.cumulative
    n = triangle.n_periods
    factors = np.empty(n - 1, dtype=np.float64)
    for j in range(n - 1):
        rows = slice(0, n - j - 1)
        below, above = data[rows, j], data[rows, j + 1]
        if method == "volume":
            total = below.sum()
            if total <= 0.0:
                raise ValueError(
                    f"development period {j} has no paid claims to develop "
                    "from; a factor off a zero base is not a factor"
                )
            factors[j] = above.sum() / total
        else:
            if np.any(below <= 0.0):
                raise ValueError(
                    f"development period {j} has an accident period with "
                    "nothing paid; a simple average cannot use it"
                )
            factors[j] = float(np.mean(above / below))
    return factors


class ChainLadder:
    """Completed square, ultimates, and the reserve they imply."""

    def __init__(self, triangle: Triangle, *, method: str = "volume",
                 tail: float = 1.0):
        if tail < 1.0:
            raise ValueError(
                f"tail factor {tail} is below 1; claims do not develop "
                "downwards after the triangle ends"
            )
        self.triangle = triangle
        self.method = method
        self.tail = float(tail)
        self.factors = development_factors(triangle, method)
        self.square = self._complete()

    def _complete(self) -> np.ndarray:
        data = np.array(self.triangle.cumulative, dtype=np.float64)
        n = self.triangle.n_periods
        for i in range(1, n):
            for j in range(n - i, n):
                data[i, j] = data[i, j - 1] * self.factors[j - 1]
        return data

    @property
    def ultimates(self) -> np.ndarray:
        return self.square[:, -1] * self.tail

    @property
    def reserve(self) -> np.ndarray:
        """Outstanding by accident period: ultimate less paid to date."""
        return self.ultimates - self.triangle.latest()

    @property
    def total_reserve(self) -> float:
        return float(self.reserve.sum())

    def future_payments(self) -> np.ndarray:
        """Expected payments by **calendar** period from the valuation date.

        Development periods run diagonally across calendar time — accident
        period ``i``'s development period ``j`` is paid in calendar period
        ``i + j`` — so a reserve cannot be discounted off the triangle's
        columns. This is the reduction onto the diagonals, and it is what
        the discounting below consumes.

        ``n − 1`` long, plus one more period carrying the tail, which is
        assumed to fall immediately after the square closes.
        """
        n = self.triangle.n_periods
        increments = np.diff(self.square, axis=1, prepend=0.0)
        payments = np.zeros(n, dtype=np.float64)
        for i in range(n):
            for j in range(n):
                calendar = i + j
                if calendar >= n:
                    payments[calendar - n] += increments[i, j]
        payments[n - 1] += float((self.tail - 1.0) * self.square[:, -1].sum())
        return payments

    def __repr__(self) -> str:
        return (f"ChainLadder({self.method}, reserve="
                f"{self.total_reserve:,.0f})")


class Measurement:
    """The LIC balance and the two lines it puts in the statements."""

    def __init__(self, *, liability, claims_paid, expense, finance_expense,
                 risk_adjustment, risk_release, discounted: bool):
        self.liability = liability
        self.claims_paid = claims_paid
        self.expense = expense
        self.finance_expense = finance_expense
        self.risk_adjustment = risk_adjustment
        self.risk_release = risk_release
        self.discounted = discounted

    @property
    def total_expense(self) -> float:
        return float(self.expense.sum() + self.finance_expense.sum())

    def residual(self) -> float:
        """Opening liability plus expense recognised, less claims paid."""
        return (float(self.liability[0]) + self.total_expense
                - float(self.claims_paid.sum()))

    def reconciles(self, tolerance: float = 1e-8) -> bool:
        """Does the run-off pay exactly what it set up and then recognised?

        The opening balance is **not** an expense of this run-off — it was
        recognised as the claims were incurred, in the period the coverage
        was provided. What the LIC recognises afterwards is only the unwind
        of the discount and the release of the risk adjustment. So the
        invariant carries the opening balance explicitly, and a version that
        left it out would be off by the whole liability.
        """
        scale = max(1.0, float(np.abs(self.claims_paid).sum()))
        return abs(self.residual()) <= tolerance * scale

    def __repr__(self) -> str:
        return (f"Measurement(LIC={self.liability[0]:,.0f}, "
                f"expense={self.total_expense:,.0f})")


def measure_lic(payments, *, curve: YieldCurve,
                risk_adjustment: RiskAdjustment | None = None,
                discounted: bool = True,
                timing: str = "end") -> Measurement:
    """Roll the liability for incurred claims forward over its run-off.

    ``payments`` are the expected claim payments on claims **already
    incurred**, one per future period. No new incurrals: this measures a
    closed cohort's run-off, which is what makes the reconciliation
    invariant a statement about the whole liability rather than about a
    window of it.

    ``discounted=False`` is §59(b)'s practical expedient — permitted where
    claims are expected to be paid within a year of being incurred. Taking
    it does not change what is paid, only when it is recognised, and
    :func:`expedient_error` measures the difference.
    """
    flows = np.asarray(payments, dtype=np.float64).ravel()
    n = flows.size
    if n == 0:
        raise ValueError("a liability with no payments is not a liability")
    if np.any(flows < 0.0):
        raise ValueError(
            "a negative claim payment is a recovery; model it as one rather "
            "than netting it into the run-off"
        )
    if timing not in TIMINGS:
        raise ValueError(f"timing must be one of {TIMINGS}, got {timing!r}")
    df = (curve.discount_factors(n + 1) if discounted
          else np.ones(n + 1, dtype=np.float64))
    paid_at = np.arange(n) if timing == "start" else np.arange(1, n + 1)

    # Value still owed at the start of each period: the tail of the
    # discounted payments, re-based to that date. Written as a re-based
    # reverse sum rather than a forward recursion because the two timings
    # discount from different dates and a single step factor cannot be
    # right for both.
    discounted_flows = flows * df[paid_at]
    tail = np.concatenate([np.cumsum(discounted_flows[::-1])[::-1], [0.0]])
    present = tail / df[:n + 1]

    margin = (risk_adjustment.balance(n) if risk_adjustment is not None
              else np.zeros(n + 1))
    release = (risk_adjustment.release(n) if risk_adjustment is not None
               else np.zeros(n))

    liability = present + margin
    unwind = np.zeros(n, dtype=np.float64)
    for t in range(n):
        unwind[t] = present[t + 1] + flows[t] - present[t]

    # Nothing new is incurred, so the only service expense is the release
    # of the risk adjustment — negative, because it is a credit to expense.
    expense = -release
    return Measurement(liability=liability, claims_paid=flows,
                       expense=expense, finance_expense=unwind,
                       risk_adjustment=margin, risk_release=release,
                       discounted=discounted)


def expedient_error(payments, curve: YieldCurve, timing: str = "end") -> float:
    """What §59(b) costs, as a share of the undiscounted liability.

    The practical expedient is permitted where claims are expected to be
    paid **within a year** of being incurred, and the question it invites
    is how far that can be stretched. This answers it in the only way that
    settles anything: the relative overstatement of the liability from not
    discounting.
    """
    flows = np.asarray(payments, dtype=np.float64).ravel()
    total = flows.sum()
    if total <= 0.0:
        raise ValueError("a liability of nothing has no discounting error")
    factors = _timed_factors(curve, flows.size, timing)
    return float(total / (flows * factors).sum() - 1.0)


def combined(*triangles: Triangle) -> Triangle:
    """Add triangles cell by cell. Same shape, or it raises.

    Provided so the non-additivity of the chain ladder can be demonstrated
    rather than described: reserving the sum is not the same as summing the
    reserves, and this is the "sum" half of that sentence.
    """
    if not triangles:
        raise ValueError("nothing to combine")
    n = triangles[0].n_periods
    if any(t.n_periods != n for t in triangles):
        raise ValueError(
            "triangles must share a shape; a book with a different history "
            "length is a different book"
        )
    total = sum(t.cumulative for t in triangles)
    return Triangle(total)


__all__ = [
    "FACTOR_METHODS", "TIMINGS", "BootstrapResult", "ChainLadder",
    "MackResult", "Measurement", "RiskAdjustment", "Triangle", "combined",
    "development_factors", "expedient_error", "mack_standard_error",
    "measure_lic", "odp_bootstrap",
]


# --------------------------------------------------------------------------
# Reserve variability: Mack (1993), and the bootstrap
# --------------------------------------------------------------------------

@dataclass(frozen=True)
class MackResult:
    """Mack's prediction errors for a chain-ladder reserve.

    ``by_period`` is the standard error of each accident period's reserve
    and ``total`` that of the whole; the two do **not** add, and the gap is
    the point of the second formula. Accident periods share the same
    development factors, so their reserves are positively correlated and the
    total's error exceeds the square root of the sum of squares — adding in
    quadrature, the natural thing to do, understates it.
    """

    by_period: np.ndarray
    total: float
    sigma_squared: np.ndarray
    reserve: np.ndarray
    total_reserve: float

    @property
    def coefficient_of_variation(self) -> np.ndarray:
        """Standard error as a fraction of each reserve.

        The form Mack's Table 3 publishes, and the one worth reporting: an
        error of 100 means nothing until it is set against the reserve it
        belongs to. Zero where the reserve is zero — the oldest accident
        period is fully developed and has no reserve to be uncertain about.
        """
        return np.divide(self.by_period, self.reserve,
                         out=np.zeros_like(self.by_period),
                         where=self.reserve != 0.0)

    @property
    def total_coefficient_of_variation(self) -> float:
        if self.total_reserve == 0.0:
            return 0.0
        return self.total / self.total_reserve

    @property
    def quadrature_total(self) -> float:
        """What adding the periods in quadrature would give.

        Computed on purpose so the correlation term can be reported rather
        than assumed away. Always **below** :attr:`total`.
        """
        return float(np.sqrt(np.sum(self.by_period ** 2)))

    def __fingerprint__(self):
        return {"by_period": self.by_period, "total": self.total,
                "sigma_squared": self.sigma_squared,
                "reserve": self.reserve,
                "total_reserve": self.total_reserve}


def mack_standard_error(ladder: ChainLadder) -> MackResult:
    """Mack (1993)'s distribution-free prediction error, exactly as published.

    *Distribution-Free Calculation of the Standard Error of Chain Ladder
    Reserve Estimates*, ASTIN Bulletin 23(2), 213–225. The estimator is
    distribution-free in the sense that matters here: it assumes only that
    ``E[C_{i,j+1} | C_{i,j}] = f_j C_{i,j}`` and that the conditional
    variance is proportional to ``C_{i,j}``, not that anything is lognormal.

    Three pieces:

    - ``σ²_j``, the proportionality constant in that variance, estimated
      from the observed factors around ``f_j``;
    - the per-period mean squared error, which carries **two** terms — the
      process variance of the future development, and the estimation
      variance of the factors themselves. The second is what a naive
      simulation of the fitted model omits;
    - the total, which adds a **correlation** term because every accident
      period is developed with the same factors.

    ``σ²`` for the final development period cannot be estimated — there is
    one observation and no degrees of freedom left — so Mack extrapolates it
    as ``min(σ⁴_{n-3}/σ²_{n-4}, σ²_{n-4}, σ²_{n-3})``, which is his §3 and
    is used here rather than a zero. Setting it to zero would declare the
    last factor known exactly, which is the one place the data says least.

    **Volume-weighted factors only.** The whole derivation is conditional on
    the volume-weighted estimator being the one used; a simple-average
    triangle has different factors and these formulae do not describe their
    error. Refused rather than computed.
    """
    if ladder.method != "volume":
        raise ValueError(
            f"Mack's formulae are derived for the volume-weighted "
            f"development factors and this ladder uses {ladder.method!r}. "
            f"The estimator is not a wrapper around whatever factors it is "
            f"given — σ² is estimated around f_j, and a different f_j is a "
            f"different model."
        )
    if ladder.tail != 1.0:
        raise ValueError(
            f"this ladder carries a tail factor of {ladder.tail}, and Mack's "
            f"formulae stop at the end of the triangle. A tail's own "
            f"uncertainty is not in the data and is not invented here."
        )
    n = ladder.triangle.n_periods
    if n < 4:
        raise ValueError(
            f"Mack's σ² extrapolation for the final development period "
            f"needs three earlier ones; a {n}-period triangle has too few"
        )
    observed = ladder.triangle.cumulative
    square = ladder.square
    factors = ladder.factors

    #: Σ_i C[i, j] over the rows that contribute to f_j — the same rows, so
    #: the estimation-variance term is scaled by the volume behind it.
    column_sums = np.array(
        [np.nansum(observed[:n - 1 - j, j]) for j in range(n - 1)],
        dtype=np.float64)

    sigma2 = np.zeros(n - 1, dtype=np.float64)
    for j in range(n - 2):
        rows = n - 1 - j
        current = observed[:rows, j]
        following = observed[:rows, j + 1]
        sigma2[j] = float(
            np.sum(current * (following / current - factors[j]) ** 2)
            / (rows - 1))
    sigma2[n - 2] = min(sigma2[n - 3] ** 2 / sigma2[n - 4],
                        sigma2[n - 4], sigma2[n - 3])

    ultimates = square[:, -1]
    mse = np.zeros(n, dtype=np.float64)
    for i in range(1, n):
        terms = range(n - 1 - i, n - 1)
        mse[i] = ultimates[i] ** 2 * sum(
            sigma2[j] / factors[j] ** 2
            * (1.0 / square[i, j] + 1.0 / column_sums[j])
            for j in terms)

    total_mse = float(mse.sum())
    for i in range(1, n):
        terms = range(n - 1 - i, n - 1)
        total_mse += float(
            ultimates[i] * ultimates[i + 1:].sum()
            * sum(2.0 * sigma2[j] / (factors[j] ** 2 * column_sums[j])
                  for j in terms))

    return MackResult(
        by_period=np.sqrt(mse), total=float(np.sqrt(total_mse)),
        sigma_squared=sigma2, reserve=ladder.reserve,
        total_reserve=ladder.total_reserve,
    )


@dataclass(frozen=True)
class BootstrapResult:
    """An over-dispersed Poisson bootstrap of the reserve distribution.

    ``reserves`` is one total reserve per simulation, in the order the
    pinned stream produced them — so the same seed gives the same array,
    element for element, which is what makes a *range* reproducible rather
    than merely stable in distribution.
    """

    reserves: np.ndarray
    seed: int
    scale: float
    point_estimate: float

    @property
    def standard_error(self) -> float:
        """Sample standard deviation of the simulated reserves.

        ``ddof=1``: these are simulations of a distribution, not the
        population itself.
        """
        return float(np.std(self.reserves, ddof=1))

    @property
    def coefficient_of_variation(self) -> float:
        if self.point_estimate == 0.0:
            return 0.0
        return self.standard_error / self.point_estimate

    def percentile(self, q) -> np.ndarray:
        """Reserve at the given percentile(s) of the simulated distribution."""
        return np.percentile(self.reserves, q)

    def __fingerprint__(self):
        return {"seed": self.seed, "scale": self.scale,
                "point_estimate": self.point_estimate,
                "n_samples": int(self.reserves.size),
                "standard_error": self.standard_error}


def odp_bootstrap(triangle: Triangle, *, n_samples: int = 1000,
                  seed: int = 0, method: str = "volume",
                  process_variance: bool = False) -> BootstrapResult:
    """England–Verrall's over-dispersed Poisson bootstrap of the reserve.

    Resample the Pearson residuals of the fitted incremental triangle,
    refit, and read off a reserve; repeat. The over-dispersion parameter
    ``φ`` is the scaled Pearson statistic, ``Σ r²/(N − p)``, and residuals
    are scaled by ``√(N/(N − p))`` so the resampled triangle carries the
    variance the fit implies rather than the smaller one the residuals show
    after the parameters have absorbed some of it.

    **The seed is an argument with a default, not a hidden global.** A
    reserve *range* that cannot be reproduced is an opinion; the same seed
    gives the same simulations element for element, and that is asserted
    rather than described.

    ``process_variance`` decides which of two different numbers comes back,
    and the default is the smaller one:

    - ``False`` — the distribution of the **fitted** reserve, the
      *estimation* error alone. This is what resampling the residuals
      measures, and on the Taylor–Ashe triangle it is about 15%.
    - ``True`` — a gamma draw with mean ``R*`` and variance ``φ R*`` around
      each simulated reserve, which adds the *process* variance of the
      future payments and gives a **prediction** error, about 16% there.

    Mack's is a prediction error, so only the second is comparable with it —
    and they still disagree, because they are different models rather than
    two estimates of one number. The default is ``False`` because a process
    step added silently would let an estimation error be quoted against a
    published prediction error and look close enough to pass.
    """
    if n_samples < 2:
        raise ValueError(
            f"a bootstrap of {n_samples} sample(s) has no distribution to "
            f"describe; the standard error would be undefined or zero"
        )
    ladder = ChainLadder(triangle, method=method)
    n = triangle.n_periods
    observed = triangle.cumulative
    upper = ~np.isnan(observed)

    # Fitted incremental claims, from the backwards recursion on the fitted
    # ultimates — the standard ODP fit, which reproduces the chain ladder.
    fitted = np.array(ladder.square, dtype=np.float64)
    for i in range(n):
        for j in range(n - 2, -1, -1):
            fitted[i, j] = fitted[i, j + 1] / ladder.factors[j]
    fitted_increments = np.diff(fitted, axis=1, prepend=0.0)
    increments = np.diff(np.where(upper, observed, np.nan), axis=1,
                         prepend=0.0)

    cells = upper
    n_cells = int(cells.sum())
    n_parameters = 2 * n - 1
    if n_cells <= n_parameters:
        raise ValueError(
            f"a {n}-period triangle has {n_cells} observations and the "
            f"model has {n_parameters} parameters; there are no degrees of "
            f"freedom for the over-dispersion to be estimated from"
        )
    with np.errstate(invalid="ignore", divide="ignore"):
        residuals = ((increments - fitted_increments)
                     / np.sqrt(np.abs(fitted_increments)))
    pool = residuals[cells & np.isfinite(residuals)]
    scale = float(np.sum(pool ** 2) / (n_cells - n_parameters))
    adjustment = np.sqrt(n_cells / (n_cells - n_parameters))

    rng = np.random.default_rng(seed)
    reserves = np.empty(n_samples, dtype=np.float64)
    for sample in range(n_samples):
        drawn = rng.choice(pool, size=n_cells, replace=True) * adjustment
        resampled = np.array(fitted_increments, dtype=np.float64)
        resampled[cells] += drawn * np.sqrt(np.abs(
            fitted_increments[cells]))
        cumulative = np.cumsum(np.where(cells, resampled, 0.0), axis=1)
        cumulative[~cells] = np.nan
        try:
            refit = ChainLadder(Triangle(cumulative), method=method)
        except ValueError:
            # A resampled triangle can go negative in a cell; the draw is
            # not a triangle and is refused rather than clipped, which would
            # bias the range toward the point estimate.
            reserves[sample] = np.nan
            continue
        reserves[sample] = refit.total_reserve

    if process_variance:
        finite = np.isfinite(reserves) & (reserves > 0.0)
        # Gamma with mean R* and variance φR*: shape R*/φ, scale φ. The
        # over-dispersed Poisson's continuous analogue, which is what lets
        # a non-integer claim amount have a Poisson-like variance.
        reserves[finite] = rng.gamma(reserves[finite] / scale, scale)

    kept = reserves[np.isfinite(reserves)]
    if kept.size < 2:
        raise ValueError(
            f"only {kept.size} of {n_samples} resampled triangles were "
            f"valid; this triangle's residuals are too large for the "
            f"bootstrap to describe it"
        )
    return BootstrapResult(reserves=kept, seed=int(seed), scale=scale,
                           point_estimate=ladder.total_reserve)
